module toDoList{
	interface toDoList{
		string register(in string name,in string password);
		string addItem(in string startTime,in string endTime,in string label);
		string queryItems(in string startTime,in string endTime);
		string deleteItem(in long index);
		string clearItems();
	};
};